apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahallu-fe
  namespace: mahallu
  labels:
    app: mahallu-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahallu-fe
  template:
    metadata:
      labels:
        app: mahallu-fe
    spec:
      volumes:
        - name: vol-piy2j
          secret:
            secretName: cm-makham-secret
            defaultMode: 420
      containers:
        - name: mahallu-fe
          image: latheefp/mahallu-fe:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
